store_type: google-cloud
timeout: 10s
port: 8080
max_request_size_mb: 100
google_auth_client_id: 602223566336-77ugev7r0br5k1j8rc8i407kb0et34al.apps.googleusercontent.com
google_auth_client_secret_id: ENC[AES256_GCM,data:fzTzsZd8Z7uc7s1HN11tOGLkxlTIF63tNX5jcM0C5rMEdcg=,iv:eMK0bMMeo2EZmz0m/5Dgw6YX7vxu1TaQxjZj0muwbB4=,tag:ufe7NXjzFbzI9MPNCz11bA==,type:str]
google_auth_rederict_url: http://localhost:8080/auth/callback
cookie_secret_sign_key: ENC[AES256_GCM,data:roKXu5GGtF3jmh2BFsSZCNckNdGsSffbK95Ia5KcpA827P2lKfZ/M4Qj291ebI/hP8If8iFZoPK5vwE=,iv:WAqxsMFxgUp0kkzldntO+No8z8uKw5Yuep3aqNzxSa0=,tag:dAV44eBBFEXsrYqCXrQTkQ==,type:str]
base_url: https://test.caesura.no
session_max_age: 1200
email_sender: noreply@caesura.no
stripe_secret_key: ENC[AES256_GCM,data:zi30ekfRNlo2yEs7upF96WD+a0tGWMHGA8utfHrPCF22SJXfAE0PUhCOn72QSsmDMg2HjymEQ0xES5WARdLkWtkcoMHXATqcPZ8QdMEeGAExehvQ/1QrZh21jyNvxatIxFreautXSLQMl8Q=,iv:HlgvJzK9WLreWBurlbHB+g4BdhcmfJyZPU1A+mLsR1M=,tag:2oEnt6jN2J4WZMGcLz5zyA==,type:str]
stripe_webhook_sign_secret: ENC[AES256_GCM,data:Gg0HH2wfiWDR6iMpBZWPv8vNbonvE+eX2RxIv9QTnsG1pupbkIOxP/iVRt4ZKNj7LOhBl5Re6+t/QA==,iv:EFGYh4g/VuMPfGFx4LNYyxLC2ufeSAgKZ9AiBLQiJG4=,tag:I9sKzwP3ySy54/L1D4ZhTA==,type:str]
require_subscription: true
brevo_api_key: ENC[AES256_GCM,data:wmpT6dTlnHYMBBE/AJE2YxTIQeAvZUjo7jCo+QzwEOVK/MjnUoTN+l6cQJ7aiTkttH0N/yr9bxHcvkVj0AkVBgRbAZrP0MWqxAPFjyYhJQlPY+Iva+pvN0jX,iv:wME/fP2dwsqWt5AElAyNmqcOompmLfhjZ/nVGChzLCc=,tag:f/y8DmUi46h4AIlqWvuG0Q==,type:str]
email_delivery_service: brevo
google_config:
    bucket: caesura-test
    projectId: caesura-466820
    environment: test
sops:
    gcp_kms:
        - resource_id: projects/caesura-466820/locations/global/keyRings/caesura-ring/cryptoKeys/sops-key
          created_at: "2025-11-20T20:37:33Z"
          enc: CiQAa0YgtOAwZu1VB/Da+AQsH0W11ZoxCerEYIQEXRAyVs04Im8SSQAi5luSpr6JiizNaOs+vLt8ShxJKiljqCbQRJ6LmJ2b1WjZySQh24757DEdqfzaCa+Ao3fefBF5GAQTUylBhVm5pDoTPCj6bl0=
    age:
        - recipient: age1rekch73u43q89fq4ajvq4utud2dp3jvvc4eefer42us4kgjal9vs2juvx7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQzY3cUZIbTdoN0lNaHIw
            VFVIcUVzNDhQYlo3a1FuZ2JkUjk2MmhtQm13Ckw4RGttNlI0MTUvaWRSUGdDVXhX
            MDNTNUFsbVZMYW8wS251SVhHTEUvYWsKLS0tIERlMDVEaEJxVDc5dWNaTVR5dFJS
            NDZqbjJDWTlBTlJCbHZTaWtYV21pOWMKjG5qLL2n1jP3NUWENHCyvUa0xkLo8JIt
            x8R45o0clXjpxQVsBX2ZVZiU7QnuoihyOwLeTF25pujgW1T7MlFVLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gvqc0qnsz7s4sfyffda6ctda4aah2drae0lvkug499hy6ckgxyvqsqcqh6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVay9HK24wUlhiR28vTWdI
            T1cxVEtoNUpUejVOWlliOG5ZdXc4S1RvSzJzCnFDckF2dWVqNkxCY0tZZFZyRXFG
            aDZySGtHUnF6QnZET2NSUDR0ZEtrQzgKLS0tIG5tSzJxdG1BSCt2d01LS1hrQWZN
            MFlWUjJaTGxuMjMyL2s3QU5zclZwUzQKAKpO4i3GgL5ekJvF+XM/+fmUxla1cuwt
            jj4HFC8vhL8bDrpftk607Gxr7ahOsjyT0qkKdYjWNGTaZx8ZFQnnew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T20:37:34Z"
    mac: ENC[AES256_GCM,data:n/hs0gRkltSXSKFB0JyR+aLOCUhulHp0fSypoedZwWvy1Ilqew0hwfF8JMQHPstYOJJKWMfJ7iRsQV6DM2luSb0GZr1ypbTrJkGd0SmfjjT1J5Bz9vbu2mCn0MLa3xjDV449qqTzAZSqeNLkNFzAOSLxyIgPBRjjMcT1B4Nu0k0=,iv:NESu2++9DSiwWgCCYEbedwhHdnSmjz+E2gZyMPPtynQ=,tag:00N4mGqN6kLajA/Lqjo1Qw==,type:str]
    encrypted_regex: (api_key|secret|password)
    version: 3.11.0
