store_type: google-cloud
timeout: 10s
port: 8080
max_request_size_mb: 150
google_auth_client_id: 602223566336-77ugev7r0br5k1j8rc8i407kb0et34al.apps.googleusercontent.com
google_auth_client_secret_id: ENC[AES256_GCM,data:n6vbcKfuvD+uk6jjDm2LCTsFDA+eEwkdu64AhJaCI2/kgrU=,iv:Yham4xTNGeCFeenZmLx9OogNMMHqGbdiipmrDmy6STM=,tag:TVF73LyEE6J+TaaldnfwZw==,type:str]
google_auth_rederict_url: https://test.caesura.no/auth/callback
cookie_secret_sign_key: ENC[AES256_GCM,data:CBq+SRfnRgpPNCIpOquMefs3DVFh1DRUWvxSKGuK5e2Zryt8mwZIB7F9s6S+fQ1tT6u9NqhCGl4A28A=,iv:uITTagYnEIrMa0VYoMiG+53fKBgHCr3QDK/jutKOKbc=,tag:s5K88hoKxhdQ5CwsDmDGhg==,type:str]
base_url: https://test.caesura.no
session_max_age: 1200
email_sender: noreply@caesura.no
stripe_secret_key: ENC[AES256_GCM,data:lsoY+iizzKaILR3GQMRIVawnZ+om1lnh9kzigZYc4kFPpR8pReTz6pwrttp5GiTC0AzkaNAntJM9JDXkj6DmIDBwp1K0yZDnhX+tVJngrJPgptXEo4I96YeYpbUo6QPPwjvSnQses8Niegw=,iv:riRymHJK8HI7L/c53GE5HETofHOelk2EFXAwmatrudI=,tag:qOlPRYCAsg+ObTc2WtT5NA==,type:str]
stripe_webhook_sign_secret: ENC[AES256_GCM,data:xbEI9Oe53MikUjMOpdkf6XPRRSy7gZ1XqgduWGVAfKpiTzduL8XcqC49kJd2FxL5bi/rvAwame3xIA==,iv:Ra8dJ1M/lwnFK8Yc4DEQ+2utZMkiIaoZAml+JdJ5tyk=,tag:ASuTdCnYCFIB3d2YmnI+IA==,type:str]
require_subscription: true
brevo_api_key: ENC[AES256_GCM,data:RtzVCDZTeA7SuiuR67IirB7ti2LbgI3U/lJ4cm3V28nSrOkZedgQoNjQF7ocEtf9na4Otbs5FVD2VePZJ/Tl11snTFj1or/FWNxx62rLAb9hlzUJmEHakFUk,iv:KAcrJZzlP6bWP53Vjs/sWgZLVTaBjGL8JMS/9qNFIuQ=,tag:q+7stdESC8l0MqH3Hdmgog==,type:str]
email_delivery_service: brevo
google_config:
    bucket: caesura-test
    projectId: caesura-466820
    environment: test
sops:
    age:
        - recipient: age1rekch73u43q89fq4ajvq4utud2dp3jvvc4eefer42us4kgjal9vs2juvx7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMlNkU0pOcWpXQlBHdlo0
            eGJvTEoxbVdaamtPNjZXTW9hTUFGejRJTkZzClY4MlMxbUdVbGoyS0s5TzFEcnYv
            WlJVTDV6YklEV3BDYzdTUW16aXRBVzAKLS0tIDhQVTJpT0JjQVN1TzRPKy9nOVpx
            N21wa0ptcVl1N0J5R1JETGI3OWp0QU0Kziu+mZWz6PpVLjGd46HyH4yP4RfWzCS/
            gJgJsIpS9A6X9jVYWJjuHh8dTV0gQ1JlFbE005JoFo+FiG6nPiWnIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gvqc0qnsz7s4sfyffda6ctda4aah2drae0lvkug499hy6ckgxyvqsqcqh6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Wk0wOEhTTFhubCs5a1hx
            ZEpFTEtYSFY0NDdtUEh5RzMzbURHVzVEaDJjClVPcXlZVWxIRW9rOHE1TFV2cjdB
            NTE2VXJrT01YNThKYUs4Z1o5ZStPQVkKLS0tIDFLcHZEUjIwNG9TdnZoZHhPS3Ew
            UHBzZStaUnM4L0UydlFtdlJGRVpmYXMKHxpS/pdf+2Qj9hCmt2zaB+wg3Od6o0gE
            ZjUAmG9kMOu1CZCdj+Ab53Gf7siL8kzJmRjjHRsa+3aIH+3ZRqp+yg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s5m5e78an6dp9sxlyjqknzx2slazw604fdw2l6jzump5w6samv5qypc5hw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBaElvUTFJZDdUbGFmN2pT
            cjZJVDFtVVp1WTZDRFExUmtEN1Z6SDBxTW1nClM1YVRFSGhGRzRuYmpaRnFER0dJ
            aFVVSkt4L1p1aUVtd0l6S1laTHVsTk0KLS0tIFFEYUtlTktsTllkSU81ZnVIeDR4
            VTlRL25DOG8ybENobUFGY0liR2dwWjQKT3pAymg5PHcR/EsR64sTgyUKyfuXruP3
            hRe+VGjZ65QbMYuvER2nVl5xOUgAC/h8dZlWNtWl1n6RNiAl4411qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T07:53:37Z"
    mac: ENC[AES256_GCM,data:QUBXqsOYniA0N7luNSfrrP+Saw8vuYuU8iD36I+p7FYm0dMqJ6wlNhfdpcz7NHqzLFmrq7gTwxl1tvSQK2pOYAoJnVC+4UHrOR3eE+9uolOcCoA+XAohzPT2abdHcXdwyg08wudmSLbbqfdkf5DNAPWVQNDzJKMSPjwjdykbF1w=,iv:mwcwuMoJmfaZ+Kg9YWuEnxvKGyN807XvtOifrwF6zPM=,tag:G5jUxMSeSDznfk2qoXbGpg==,type:str]
    encrypted_regex: (api_key|secret|password)
    version: 3.11.0
