store_type: in-memory
timeout: 10s
port: 8080
max_request_size_mb: 100
google_auth_client_id: 602223566336-77ugev7r0br5k1j8rc8i407kb0et34al.apps.googleusercontent.com
google_auth_client_secret_id: ENC[AES256_GCM,data:EkGUgZNz1YTIjByZHs7h3v0UyOw5uBdv8Cew+UsDePmGjHM=,iv:9s7j6TLSWzGE8HMuy4pGUBcDrjcdsIPznBXRSjfmkto=,tag:Yz70CrVgay6Yhq/Eu+pPsQ==,type:str]
google_auth_rederict_url: http://localhost:8080/auth/callback
cookie_secret_sign_key: ENC[AES256_GCM,data:8fZlZWQocDwTTKxOaFuVDraOXHSgbHg7jv0iE3Px1VAtLeCwgsA+nzyJiSreoMqwIdszYQx+n//E77Q=,iv:pvQcmiZOhlLsCPOWtc/TQHNJubGuEOodVAGvlhAJce8=,tag:ao58ksNduaRdZMrZNrzQaA==,type:str]
base_url: http://localhost:8080
session_max_age: 3600
email_sender: noreply@caesura.no
stripe_secret_key: ENC[AES256_GCM,data:ys1jm9t00zAu+yd4CDGg1KfeGR4j+9ivFjXkTJYzE0C1EsoqOyiISToX0IXiO/BfmqFqX2TdUB6OyiI0cB6DswJbHiuFjq/hLjq0nQyPd6LIMK3Fqat4A+VhHCot4ievJ3AKB49kWnkeRNw=,iv:lTC2QgYzSpRb5Zc9yY/r2prd8AbyqbkVp59B+AdLReE=,tag:ch1WvYRXuMKQgRAOpsX/+w==,type:str]
stripe_webhook_sign_secret: ENC[AES256_GCM,data:eNui0vLTBEeWvpz+e1T7AT1bHqE68Vmi6/WZ6ri3DrLcYCQt2Is4v9on7BhyLR4f/7VSYA8hu7zUJg==,iv:K26Ylq9aS601FRFJ2a9fRT6Lh9vK+kbjk7V02uhsZ1s=,tag:cH9GegNii7m8UnX0mmQHFw==,type:str]
require_subscription: false
brevo_api_key: ENC[AES256_GCM,data:pQ89Ktpo5uy/rHT5e8RipTpWzA+Wz8YXFd1K7RRrOaV44AKoC/ZMSvJEW/nTbypIlL8Z5Bcq9hOUz5jVLRS4lgV6xQEVcyFQ0IdUPu3Q6ppoTlsJ0mn6CAAw,iv:bSS21AXxnjSVj8zFYX6tsQT83osaTvCVXyYmm10yBmU=,tag:ZTsGwrpCWPLiSV4KaISmSg==,type:str]
email_delivery_service: brevo
google_config:
    bucket: caesura-test
    projectId: caesura-466820
    environment: test
sops:
    gcp_kms:
        - resource_id: projects/caesura-466820/locations/global/keyRings/caesura-ring/cryptoKeys/sops-key
          created_at: "2025-11-20T17:59:39Z"
          enc: CiQAa0YgtOUzzIkcWv5W0Jf/fJnKwSLZzsd6rxuJtSfW8ojXnV0SSQAi5luSAyVLMwxBOTklXNPi2wF5twUfpOwd4fJfMydm1n691LeTJqrWss4JBIxu4zr9c56eZOsgB/2eLe4I0Vd06zD6RT3h318=
    age:
        - recipient: age1rekch73u43q89fq4ajvq4utud2dp3jvvc4eefer42us4kgjal9vs2juvx7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYnJwbjdMNTJKdE5XdHhz
            VXlKdFRESm51Q1dnSUhGQnk1WFNYQkhsM2k0CmJFZ2xxbWJsUHVXU2VQRFczTWpw
            dlBLMitmWGRlT3Z1a1hCMlJJSUQxUWcKLS0tIDl3dFJvTDlURld1WG51TjdKZEJt
            MkxMRE9PUCs2dE9pRTRsVFRGWlIrVHcKnP57YPVZjebFO18Wlvny2GNByszG/uRR
            jJQVQj+G10Nk6FP+L/qlkK0O96bOvxTcgl6JK04p3u2w8KMzDcx9BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T17:59:40Z"
    mac: ENC[AES256_GCM,data:TVH3+TfBHqjMVznxcUxIIylkfsp/3Z02iGhvCZkqTSx5JzRuwg/U/pSmtOJ+vPwamrTIQHouKOJ6BAZNdfqAWvCgQ87p6kqlFb6wghyb+J3VNHxmucoro8Huf87tt+hZ5nEAlbOW6KmVyKvE3zEyue41QFTjQZgdmRmmer0QKGg=,iv:sTOqNSSQARqRfOpsTxM9Ah+LnY8amwiG5wjXLVQ0qK0=,tag:EGOGvK5rTqiCZD463V2Dzw==,type:str]
    encrypted_regex: (api_key|secret|password)
    version: 3.11.0
