store_type: large-demo
timeout: 10s
port: 8080
max_request_size_mb: 100
google_auth_client_id: 602223566336-77ugev7r0br5k1j8rc8i407kb0et34al.apps.googleusercontent.com
google_auth_client_secret_id: ENC[AES256_GCM,data:ErkXJc4rcsMpMy2VOSag6o4tV/uc2W5hDFgz30ITx/Lwm+Y=,iv:jaKUoHPhYBFAB9EzvJeX8eDoFmYNp81RgTJnr+ntYo8=,tag:glGO/YsaYrPcBmoqfPY6Fw==,type:str]
google_auth_rederict_url: http://localhost:8080/auth/callback
cookie_secret_sign_key: ENC[AES256_GCM,data:UxGM0sH7wFciNGNteZscx3GTPaLBhVnG9GtUj0R1eGSSs3j5FIUJYvvHkTjqtwjWbdT/KfiZWUAp7jk=,iv:72MiHLnIrIisFrZo9sNGLSsNBZK6HHs0o4rveW13DS4=,tag:4QBpHB0DzkKk7b3Gq5us/g==,type:str]
base_url: http://localhost:8080
session_max_age: 3600
email_sender: noreply@caesura.no
stripe_secret_key: ENC[AES256_GCM,data:aQ9WN+FZVWGyQcGYp6tAYF676GhAKATxg6fj4Wn2tzDwxejx+KeYHQ0YP5OPckqSoZbjnGwsrWOS/ydAJNz2pwJXw8/e1HnBMyAGAWPm9IkkGahZ++AhMyHlQ1cAJ6h1mZCvmErmwIg9dcU=,iv:R6KBw7/oTbDfIPB4UIS6NxkPvtreVAGyrN4IUdFMr2I=,tag:Hh7Gds+ETMbkrtBTXjt+8w==,type:str]
stripe_webhook_sign_secret: ENC[AES256_GCM,data:E76M75aFgmZfEVPWRbC7j8hwlX3k3L8jy4MUZoqPZNECKCMVJKerihSFGGbdP77OMP1DdQDwEyE9yA==,iv:yc7A7+HxEQDXlSUG6mTXE6Nw7iWx3SZblNCOaNGEUXU=,tag:u6caVtLJJta+DbaCieW9nw==,type:str]
require_subscription: false
brevo_api_key: ENC[AES256_GCM,data:taZFJBeg977oLg/pC9cYtFw8rf4wTlGJkBaAFHqjVZB9mW1DTW0bvs93YYuXGs8qDWFe9fCHgBc6It+FkyB8v73LYqljniDZkYHwbqPf8xXIHc+lPlqVaEdB,iv:Kp5hMXobPmJPDpEx5fcm5pwBnNpxfKxs4pJXldBGD1s=,tag:gXv2CrGaUhqonzaGPGoMxA==,type:str]
email_delivery_service: brevo
google_config:
    bucket: caesura-test
    projectId: caesura-466820
    environment: test
sops:
    age:
        - recipient: age1rekch73u43q89fq4ajvq4utud2dp3jvvc4eefer42us4kgjal9vs2juvx7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSemZKVG1nMWNjNnZRTUJx
            RnY2NzVwbGQ0TDd0ZUVZRWVkNXJRSDVZTldRClZZYUtmUDBHQUlWcDFjem1VUmkz
            KzJFL2lYSlZENm5KSE4wcmVJY0U5NDgKLS0tIEgxT3dOTUhMZ0g3V2VSYUNwUGVs
            VW5RS3ltWnVabE9rbERlc21MaEpCUVEKKUaKgXHdSmzJXjObmg3RH9QZ35apOQms
            pLgmbG7Zt78thoLUOfm4E/N63SH2f1CSH1m7LEXTCGwmxtGHXfsbMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gvqc0qnsz7s4sfyffda6ctda4aah2drae0lvkug499hy6ckgxyvqsqcqh6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWR0ovQ2ZmZjJsSW4xSmpj
            VlpscEtYR1dRT29KaUY5bWJiRWprcTNMMkdZCkljYzJJY0ppU09VQUpWTUZzS1V3
            bHNLajl3OTloZkhvZlpFek1qdlhaV3cKLS0tIHZlWGRDKzlSdGtjMGhaM3dPNWpK
            V0F2VWgxYXpacjBpYWhwUlZxQkkzakEKONY7hki0xu6YofHXYQZvSSQgDNjNjLSF
            8DSRYfWA9kbBynZqKvUvFo83WxvBh7VBIpnOwMpxKRMisxoXkxfo3Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s5m5e78an6dp9sxlyjqknzx2slazw604fdw2l6jzump5w6samv5qypc5hw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UnB0V01RWHVjSnkrMW9h
            TWpNcHRXUUpoczg0MjhHNUNrUmJVQmgwN0JBCkEvanc2MDJOeG9hOUFjNzE4UUIr
            MlkwK0NZYVEzcENUeVhFWjdPZ1BkY3cKLS0tIG1qQ1NLZThIMXJDb2YzSVI5anp4
            TGJrRTUvbW5QY1VROG1BVnVKRDJYWFEKVuumiR8vUpPwBsFoIHIKrYpL2ABXbLJK
            TCCbtu97DlYqVe00ar5sUPvHe2TXb7I7xCQcAlCS6JKh1GcDVtvtbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T07:53:36Z"
    mac: ENC[AES256_GCM,data:r+VamN/x48+C7TBesr1DevTzVWA35Pa7Z7zRx3C8Iev1VBrAZzeqKV/LIsgu5SpoA1Q/IOhFVSAxeY5NGEnUjM4SJaZJCKIeWIZF6YV/F5LKdh/OfMv3VS3m72T7zNg7e+gNIveYdrHkeDQn+/rl84LWfDyjLyl9d0qtYqwDOHE=,iv:oFIpElU4J9euiSCbfwtWrDMzGiUt+4/uxl2xSQ1Fce8=,tag:bkkFJWMKcQyRdMDexjSdfw==,type:str]
    encrypted_regex: (api_key|secret|password)
    version: 3.11.0
