name: Release

on:
  schedule:
    - cron: '0 4 1 * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    uses: davidkleiven/gh-workflows/.github/workflows/semantic-gh-release.yml@main
    secrets: inherit

  summarize-release:
    runs-on: ubuntu-latest
    needs: release
    steps:
     - name: Debug release outputs
       run: |
         echo "release_created: ${{ needs.release.outputs.release_created }}"
         echo "new_tag: ${{ needs.release.outputs.new_tag }}"

  build-and-push:
    needs: release
    if: ${{ needs.release.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: Build Go binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o caesura main.go

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/caesura:${{ needs.release.outputs.new_tag }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/caesura:${{ needs.release.outputs.new_tag }}

  deploy-test:
    permissions:
      id-token: write
      contents: read
    needs: build-and-push
    uses: davidkleiven/gh-workflows/.github/workflows/gcloud-deploy.yml@main
    secrets: inherit
    with:
      cloud_run_service: caesura-test
      region: europe-north1
      workload_identity_provider: projects/602223566336/locations/global/workloadIdentityPools/github-pool/providers/github-provider
      service_account: caesura-test-sp@caesura-466820.iam.gserviceaccount.com
      image: ghcr.io/${{ github.repository_owner }}/caesura:latest
      env_vars: CAESURA_PROFILE=test
      port: 8080
